USE ratp;
INSERT INTO line(id_line, line_number, line_name) VALUES ('0','10',"(Gare d'Austerlitz/Boulogne - Pont de Saint Cloud)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('1','11',"(Châtelet/Mairie des Lilas)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('2','12',"(Front Populaire/Mairie d'Issy)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('3','13',"(Saint-Denis - Universite / Les Courtilles (Asnieres - Gennevilliers)/Châtillon - Montrouge)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('4','14',"(Olympiades/Saint-Lazare)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('5','1',"(La Défense/Château de Vincennes)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('6','2',"(Porte Dauphine (Maréchal de Lattre de Ta/Nation)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('7','3B',"(Gambetta/Porte des Lilas)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('8','3',"(Pont de Levallois - Bécon/Gallieni (Parc de Bagnolet))");
INSERT INTO line(id_line, line_number, line_name) VALUES ('9','4',"(Mairie de Montrouge/Porte de Clignancourt)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('10','5',"(Place d'Italie/Bobigny - Pablo Picasso)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('11','6',"(Charles de Gaulle - Etoile/Nation)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('12','7B',"(Louis Blanc/Pré-Saint-Gervais)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('13','7',"(Villejuif - Louis Aragon / Mairie d'Ivry/La Courneuve - 8 mai 1945)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('14','8',"(Pointe du Lac/Balard)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('15','9',"(Mairie de Montreuil/Pont de Sèvres)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('16','FUN',"(Gare haute/Gare basse)");
INSERT INTO line(id_line, line_number, line_name) VALUES ('17','ORV',"(Orly-Sud/Antony)");
INSERT INTO station(id_station, station_name) VALUES ('1975',"Abbesses");
INSERT INTO station(id_station, station_name) VALUES ('1981',"Alésia");
INSERT INTO station(id_station, station_name) VALUES ('1978',"Alexandre-Dumas");
INSERT INTO station(id_station, station_name) VALUES ('1980',"Alma-Marceau");
INSERT INTO station(id_station, station_name) VALUES ('1982',"Anatole-France");
INSERT INTO station(id_station, station_name) VALUES ('11037',"Antony");
INSERT INTO station(id_station, station_name) VALUES ('1984',"Anvers");
INSERT INTO station(id_station, station_name) VALUES ('1986',"Argentine");
INSERT INTO station(id_station, station_name) VALUES ('1988',"Arts-et-Métiers");
INSERT INTO station(id_station, station_name) VALUES ('225437',"Asnieres-Gennevilliers Les Courtilles");
INSERT INTO station(id_station, station_name) VALUES ('1989',"Assemblée Nationale");
INSERT INTO station(id_station, station_name) VALUES ('1992',"Aubervilliers Pantin (4 Chemins)");
INSERT INTO station(id_station, station_name) VALUES ('1994',"Avenue Emile-Zola");
INSERT INTO station(id_station, station_name) VALUES ('1995',"Avron");
INSERT INTO station(id_station, station_name) VALUES ('1997',"Balard");
INSERT INTO station(id_station, station_name) VALUES ('1999',"Barbès-Rochechouart");
INSERT INTO station(id_station, station_name) VALUES ('50622',"Basilique de Saint-Denis");
INSERT INTO station(id_station, station_name) VALUES ('2000',"Bastille");
INSERT INTO station(id_station, station_name) VALUES ('2003',"Bel-Air");
INSERT INTO station(id_station, station_name) VALUES ('2004',"Belleville");
INSERT INTO station(id_station, station_name) VALUES ('1938',"Bérault");
INSERT INTO station(id_station, station_name) VALUES ('2005',"Bercy");
INSERT INTO station(id_station, station_name) VALUES ('51020',"Bibliotheque-Francois Mitterrand");
INSERT INTO station(id_station, station_name) VALUES ('2006',"Billancourt");
INSERT INTO station(id_station, station_name) VALUES ('2007',"Bir-Hakeim (Grenelle)");
INSERT INTO station(id_station, station_name) VALUES ('2009',"Blanche");
INSERT INTO station(id_station, station_name) VALUES ('2010',"Bobigny-Pablo-Picasso");
INSERT INTO station(id_station, station_name) VALUES ('2011',"Bobigny-Pantin (Raymond Queneau)");
INSERT INTO station(id_station, station_name) VALUES ('2012',"Boissière");
INSERT INTO station(id_station, station_name) VALUES ('2014',"Bolivar");
INSERT INTO station(id_station, station_name) VALUES ('2015',"Bonne Nouvelle");
INSERT INTO station(id_station, station_name) VALUES ('2016',"Botzaris");
INSERT INTO station(id_station, station_name) VALUES ('2017',"Boucicaut");
INSERT INTO station(id_station, station_name) VALUES ('2018',"Boulogne-Jean-Jaurès");
INSERT INTO station(id_station, station_name) VALUES ('2019',"Boulogne Pont de Saint-Cloud");
INSERT INTO station(id_station, station_name) VALUES ('1930',"Bourse");
INSERT INTO station(id_station, station_name) VALUES ('1933',"Bréguet-Sabin");
INSERT INTO station(id_station, station_name) VALUES ('1931',"Brochant");
INSERT INTO station(id_station, station_name) VALUES ('1936',"Buttes-Chaumont");
INSERT INTO station(id_station, station_name) VALUES ('1937',"Buzenval");
INSERT INTO station(id_station, station_name) VALUES ('1939',"Cadet");
INSERT INTO station(id_station, station_name) VALUES ('1940',"Cambronne");
INSERT INTO station(id_station, station_name) VALUES ('1941',"Campo-Formio");
INSERT INTO station(id_station, station_name) VALUES ('1942',"Cardinal-Lemoine");
INSERT INTO station(id_station, station_name) VALUES ('228266',"Carrefour-Pleyel");
INSERT INTO station(id_station, station_name) VALUES ('1944',"Censier-Daubenton");
INSERT INTO station(id_station, station_name) VALUES ('1949',"Champs-Elysées-Clémenceau");
INSERT INTO station(id_station, station_name) VALUES ('1950',"Chardon-Lagache");
INSERT INTO station(id_station, station_name) VALUES ('1951',"Charenton-Ecoles");
INSERT INTO station(id_station, station_name) VALUES ('1953',"Charles de Gaulle-Etoile");
INSERT INTO station(id_station, station_name) VALUES ('1952',"Charles Michels");
INSERT INTO station(id_station, station_name) VALUES ('1955',"Charonne");
INSERT INTO station(id_station, station_name) VALUES ('1961',"Château d'Eau");
INSERT INTO station(id_station, station_name) VALUES ('1962',"Château de Vincennes");
INSERT INTO station(id_station, station_name) VALUES ('1963',"Château Landon");
INSERT INTO station(id_station, station_name) VALUES ('1960',"Château Rouge");
INSERT INTO station(id_station, station_name) VALUES ('1964',"Châtelet");
INSERT INTO station(id_station, station_name) VALUES ('1968',"Châtillon Montrouge");
INSERT INTO station(id_station, station_name) VALUES ('1957',"Chaussée d'Antin (La Fayette)");
INSERT INTO station(id_station, station_name) VALUES ('1958',"Chemin Vert");
INSERT INTO station(id_station, station_name) VALUES ('1959',"Chevaleret");
INSERT INTO station(id_station, station_name) VALUES ('1969',"Cité");
INSERT INTO station(id_station, station_name) VALUES ('54244',"Cluny-La Sorbonne");
INSERT INTO station(id_station, station_name) VALUES ('1972',"Colonel Fabien");
INSERT INTO station(id_station, station_name) VALUES ('1973',"Commerce");
INSERT INTO station(id_station, station_name) VALUES ('1885',"Concorde");
INSERT INTO station(id_station, station_name) VALUES ('1887',"Convention");
INSERT INTO station(id_station, station_name) VALUES ('1888',"Corentin-Cariou");
INSERT INTO station(id_station, station_name) VALUES ('1889',"Corentin-Celton");
INSERT INTO station(id_station, station_name) VALUES ('1890',"Corvisart");
INSERT INTO station(id_station, station_name) VALUES ('1892',"Courcelles");
INSERT INTO station(id_station, station_name) VALUES ('1893',"Couronnes");
INSERT INTO station(id_station, station_name) VALUES ('50055',"Cour Saint-Emilion");
INSERT INTO station(id_station, station_name) VALUES ('1897',"Créteil-L'Echat (Hôpital Henri Mondor)");
INSERT INTO station(id_station, station_name) VALUES ('1898',"Créteil-Préfecture (Hôtel de Ville)");
INSERT INTO station(id_station, station_name) VALUES ('1899',"Créteil-Université");
INSERT INTO station(id_station, station_name) VALUES ('1894',"Crimée");
INSERT INTO station(id_station, station_name) VALUES ('1896',"Croix-de-Chavaux (Jacques Duclos)");
INSERT INTO station(id_station, station_name) VALUES ('1900',"Danube");
INSERT INTO station(id_station, station_name) VALUES ('1901',"Daumesnil (Félix Eboué)");
INSERT INTO station(id_station, station_name) VALUES ('1902',"Denfert-Rochereau");
INSERT INTO station(id_station, station_name) VALUES ('1906',"Dugommier");
INSERT INTO station(id_station, station_name) VALUES ('1907',"Dupleix");
INSERT INTO station(id_station, station_name) VALUES ('1908',"Duroc");
INSERT INTO station(id_station, station_name) VALUES ('1909',"Ecole Militaire");
INSERT INTO station(id_station, station_name) VALUES ('23674',"Ecole Vétérinaire de Maisons-Alfort");
INSERT INTO station(id_station, station_name) VALUES ('1910',"Edgar-Quinet");
INSERT INTO station(id_station, station_name) VALUES ('1911',"Eglise d'Auteuil");
INSERT INTO station(id_station, station_name) VALUES ('1912',"Eglise de Pantin");
INSERT INTO station(id_station, station_name) VALUES ('1913',"Esplanade de la Défense");
INSERT INTO station(id_station, station_name) VALUES ('1914',"Etienne Marcel");
INSERT INTO station(id_station, station_name) VALUES ('1915',"Europe");
INSERT INTO station(id_station, station_name) VALUES ('1916',"Exelmans");
INSERT INTO station(id_station, station_name) VALUES ('1917',"Faidherbe-Chaligny");
INSERT INTO station(id_station, station_name) VALUES ('1918',"Falguière");
INSERT INTO station(id_station, station_name) VALUES ('1925',"Félix Faure");
INSERT INTO station(id_station, station_name) VALUES ('1919',"Filles du Calvaire");
INSERT INTO station(id_station, station_name) VALUES ('1923',"Fort d'Aubervilliers");
INSERT INTO station(id_station, station_name) VALUES ('1924',"Franklin-Roosevelt");
INSERT INTO station(id_station, station_name) VALUES ('454595',"Front Populaire");
INSERT INTO station(id_station, station_name) VALUES ('2021',"Funiculaire Gare basse");
INSERT INTO station(id_station, station_name) VALUES ('2022',"Funiculaire Gare haute");
INSERT INTO station(id_station, station_name) VALUES ('22443',"Gabriel-Péri");
INSERT INTO station(id_station, station_name) VALUES ('1927',"Gaité");
INSERT INTO station(id_station, station_name) VALUES ('1928',"Gallieni (Parc de Bagnolet)");
INSERT INTO station(id_station, station_name) VALUES ('1929',"Gambetta");
INSERT INTO station(id_station, station_name) VALUES ('1838',"Gare d'Austerlitz");
INSERT INTO station(id_station, station_name) VALUES ('1841',"Gare de l'Est (Verdun)");
INSERT INTO station(id_station, station_name) VALUES ('1839',"Gare de Lyon");
INSERT INTO station(id_station, station_name) VALUES ('1842',"Gare du Nord");
INSERT INTO station(id_station, station_name) VALUES ('1844',"Garibaldi");
INSERT INTO station(id_station, station_name) VALUES ('1846',"George V");
INSERT INTO station(id_station, station_name) VALUES ('1848',"Glacière");
INSERT INTO station(id_station, station_name) VALUES ('1849',"Goncourt (Hôpital Saint-Louis)");
INSERT INTO station(id_station, station_name) VALUES ('1671',"Grands Boulevards");
INSERT INTO station(id_station, station_name) VALUES ('1851',"Guy-Môquet");
INSERT INTO station(id_station, station_name) VALUES ('1852',"Havre-Caumartin");
INSERT INTO station(id_station, station_name) VALUES ('1853',"Hoche");
INSERT INTO station(id_station, station_name) VALUES ('1855',"Hôtel de Ville");
INSERT INTO station(id_station, station_name) VALUES ('1858',"Iéna");
INSERT INTO station(id_station, station_name) VALUES ('1857',"Invalides");
INSERT INTO station(id_station, station_name) VALUES ('1859',"Jacques-Bonsergent");
INSERT INTO station(id_station, station_name) VALUES ('1860',"Jasmin");
INSERT INTO station(id_station, station_name) VALUES ('1861',"Jaurès");
INSERT INTO station(id_station, station_name) VALUES ('1862',"Javel-André-Citroen");
INSERT INTO station(id_station, station_name) VALUES ('1864',"Jourdain");
INSERT INTO station(id_station, station_name) VALUES ('1865',"Jules Joffrin");
INSERT INTO station(id_station, station_name) VALUES ('1866',"Jussieu");
INSERT INTO station(id_station, station_name) VALUES ('1867',"Kléber");
INSERT INTO station(id_station, station_name) VALUES ('1868',"La Chapelle");
INSERT INTO station(id_station, station_name) VALUES ('1869',"La Courneuve-8-Mai-1945");
INSERT INTO station(id_station, station_name) VALUES ('1850',"La Défense (Grande Arche)");
INSERT INTO station(id_station, station_name) VALUES ('1872',"La Fourche");
INSERT INTO station(id_station, station_name) VALUES ('1879',"Lamarck-Caulaincourt");
INSERT INTO station(id_station, station_name) VALUES ('1874',"La Motte-Picquet-Grenelle");
INSERT INTO station(id_station, station_name) VALUES ('1876',"La Muette");
INSERT INTO station(id_station, station_name) VALUES ('54166',"La Tour-Maubourg");
INSERT INTO station(id_station, station_name) VALUES ('1882',"Laumière");
INSERT INTO station(id_station, station_name) VALUES ('1798',"Ledru-Rollin");
INSERT INTO station(id_station, station_name) VALUES ('1793',"Le Kremlin-Bicêtre");
INSERT INTO station(id_station, station_name) VALUES ('1795',"Le Peletier");
INSERT INTO station(id_station, station_name) VALUES ('225436',"Les Agnettes");
INSERT INTO station(id_station, station_name) VALUES ('1800',"Les Gobelins");
INSERT INTO station(id_station, station_name) VALUES ('1801',"Les Halles");
INSERT INTO station(id_station, station_name) VALUES ('1802',"Les Sablons (Jardin d'acclimatation)");
INSERT INTO station(id_station, station_name) VALUES ('1803',"Liberté");
INSERT INTO station(id_station, station_name) VALUES ('1804',"Liège");
INSERT INTO station(id_station, station_name) VALUES ('1806',"Louis Blanc");
INSERT INTO station(id_station, station_name) VALUES ('1807',"Louise Michel");
INSERT INTO station(id_station, station_name) VALUES ('1808',"Lourmel");
INSERT INTO station(id_station, station_name) VALUES ('1809',"Louvre-Rivoli");
INSERT INTO station(id_station, station_name) VALUES ('1812',"Mabillon");
INSERT INTO station(id_station, station_name) VALUES ('1813',"Madeleine");
INSERT INTO station(id_station, station_name) VALUES ('1816',"Mairie de Clichy");
INSERT INTO station(id_station, station_name) VALUES ('1817',"Mairie de Montreuil");
INSERT INTO station(id_station, station_name) VALUES ('466736',"Mairie de Montrouge");
INSERT INTO station(id_station, station_name) VALUES ('1818',"Mairie de Saint-Ouen");
INSERT INTO station(id_station, station_name) VALUES ('1819',"Mairie des Lilas");
INSERT INTO station(id_station, station_name) VALUES ('1814',"Mairie d'Issy");
INSERT INTO station(id_station, station_name) VALUES ('1815',"Mairie d'Ivry");
INSERT INTO station(id_station, station_name) VALUES ('1820',"Maison Blanche");
INSERT INTO station(id_station, station_name) VALUES ('21583',"Maisons-Alfort-Les Juilliottes");
INSERT INTO station(id_station, station_name) VALUES ('21582',"Maisons-Alfort-Stade");
INSERT INTO station(id_station, station_name) VALUES ('22442',"Malakoff-Plateau de Vanves");
INSERT INTO station(id_station, station_name) VALUES ('22441',"Malakoff-Rue Etienne Dolet");
INSERT INTO station(id_station, station_name) VALUES ('1826',"Malesherbes");
INSERT INTO station(id_station, station_name) VALUES ('55372',"Maraichers");
INSERT INTO station(id_station, station_name) VALUES ('1828',"Marcadet-Poissonniers");
INSERT INTO station(id_station, station_name) VALUES ('1829',"Marcel Sembat");
INSERT INTO station(id_station, station_name) VALUES ('1831',"Marx-Dormoy");
INSERT INTO station(id_station, station_name) VALUES ('1834',"Maubert-Mutualité");
INSERT INTO station(id_station, station_name) VALUES ('1754',"Ménilmontant");
INSERT INTO station(id_station, station_name) VALUES ('1836',"Michel-Ange-Auteuil");
INSERT INTO station(id_station, station_name) VALUES ('1837',"Michel-Ange-Molitor");
INSERT INTO station(id_station, station_name) VALUES ('1835',"Michel Bizot");
INSERT INTO station(id_station, station_name) VALUES ('1746',"Mirabeau");
INSERT INTO station(id_station, station_name) VALUES ('1747',"Miromesnil");
INSERT INTO station(id_station, station_name) VALUES ('1749',"Monceau");
INSERT INTO station(id_station, station_name) VALUES ('1750',"Montgallet");
INSERT INTO station(id_station, station_name) VALUES ('1751',"Montparnasse-Bienvenue");
INSERT INTO station(id_station, station_name) VALUES ('1753',"Mouton-Duvernet");
INSERT INTO station(id_station, station_name) VALUES ('1758',"Nation");
INSERT INTO station(id_station, station_name) VALUES ('1761',"Nationale");
INSERT INTO station(id_station, station_name) VALUES ('1767',"Notre-Dame de Lorette");
INSERT INTO station(id_station, station_name) VALUES ('1768',"Notre-Dame des Champs");
INSERT INTO station(id_station, station_name) VALUES ('1769',"Oberkampf");
INSERT INTO station(id_station, station_name) VALUES ('1770',"Odéon");
INSERT INTO station(id_station, station_name) VALUES ('171507',"Olympiades");
INSERT INTO station(id_station, station_name) VALUES ('1771',"Opéra");
INSERT INTO station(id_station, station_name) VALUES ('11038',"Orly-Ouest");
INSERT INTO station(id_station, station_name) VALUES ('11039',"Orly-Sud");
INSERT INTO station(id_station, station_name) VALUES ('1773',"Ourcq");
INSERT INTO station(id_station, station_name) VALUES ('1774',"Palais-Royal (Musée du Louvre)");
INSERT INTO station(id_station, station_name) VALUES ('1779',"Parmentier");
INSERT INTO station(id_station, station_name) VALUES ('1780',"Passy");
INSERT INTO station(id_station, station_name) VALUES ('1781',"Pasteur");
INSERT INTO station(id_station, station_name) VALUES ('1782',"Pelleport");
INSERT INTO station(id_station, station_name) VALUES ('1740',"Péreire");
INSERT INTO station(id_station, station_name) VALUES ('1741',"Père-Lachaise");
INSERT INTO station(id_station, station_name) VALUES ('1783',"Pernéty");
INSERT INTO station(id_station, station_name) VALUES ('1784',"Philippe Auguste");
INSERT INTO station(id_station, station_name) VALUES ('1785',"Picpus");
INSERT INTO station(id_station, station_name) VALUES ('1786',"Pierre et Marie Curie");
INSERT INTO station(id_station, station_name) VALUES ('1787',"Pigalle");
INSERT INTO station(id_station, station_name) VALUES ('1790',"Place de Clichy");
INSERT INTO station(id_station, station_name) VALUES ('1792',"Place des Fêtes");
INSERT INTO station(id_station, station_name) VALUES ('1789',"Place d'Italie");
INSERT INTO station(id_station, station_name) VALUES ('1788',"Place Monge (Jardin des Plantes)");
INSERT INTO station(id_station, station_name) VALUES ('1705',"Plaisance");
INSERT INTO station(id_station, station_name) VALUES ('397629',"Pointe du Lac");
INSERT INTO station(id_station, station_name) VALUES ('1706',"Poissonnière");
INSERT INTO station(id_station, station_name) VALUES ('1708',"Pont de Levallois-Bécon");
INSERT INTO station(id_station, station_name) VALUES ('1709',"Pont de Neuilly");
INSERT INTO station(id_station, station_name) VALUES ('1710',"Pont de Sèvres");
INSERT INTO station(id_station, station_name) VALUES ('1711',"Pont Marie (Cité des Arts)");
INSERT INTO station(id_station, station_name) VALUES ('1712',"Pont Neuf");
INSERT INTO station(id_station, station_name) VALUES ('1714',"Porte Dauphine (Maréchal de Lattre de Tassigny)");
INSERT INTO station(id_station, station_name) VALUES ('1717',"Porte d'Auteuil");
INSERT INTO station(id_station, station_name) VALUES ('1721',"Porte de Bagnolet");
INSERT INTO station(id_station, station_name) VALUES ('1722',"Porte de Champerret");
INSERT INTO station(id_station, station_name) VALUES ('1723',"Porte de Charenton");
INSERT INTO station(id_station, station_name) VALUES ('1724',"Porte de Choisy");
INSERT INTO station(id_station, station_name) VALUES ('1725',"Porte de Clichy");
INSERT INTO station(id_station, station_name) VALUES ('1726',"Porte de Clignancourt");
INSERT INTO station(id_station, station_name) VALUES ('1734',"Porte de la Chapelle");
INSERT INTO station(id_station, station_name) VALUES ('1735',"Porte de la Villette");
INSERT INTO station(id_station, station_name) VALUES ('1727',"Porte de Montreuil");
INSERT INTO station(id_station, station_name) VALUES ('1728',"Porte de Pantin");
INSERT INTO station(id_station, station_name) VALUES ('1729',"Porte de Saint-Cloud");
INSERT INTO station(id_station, station_name) VALUES ('1730',"Porte de Saint-Ouen");
INSERT INTO station(id_station, station_name) VALUES ('1736',"Porte des Lilas");
INSERT INTO station(id_station, station_name) VALUES ('1731',"Porte de Vanves");
INSERT INTO station(id_station, station_name) VALUES ('1732',"Porte de Versailles");
INSERT INTO station(id_station, station_name) VALUES ('1733',"Porte de Vincennes");
INSERT INTO station(id_station, station_name) VALUES ('1718',"Porte d'Italie");
INSERT INTO station(id_station, station_name) VALUES ('1719',"Porte d'Ivry");
INSERT INTO station(id_station, station_name) VALUES ('1715',"Porte Dorée");
INSERT INTO station(id_station, station_name) VALUES ('1720',"Porte d'Orléans (Général Leclerc)");
INSERT INTO station(id_station, station_name) VALUES ('1716',"Porte Maillot");
INSERT INTO station(id_station, station_name) VALUES ('1737',"Pré-Saint-Gervais");
INSERT INTO station(id_station, station_name) VALUES ('1738',"Pyramides");
INSERT INTO station(id_station, station_name) VALUES ('50047',"Pyramides");
INSERT INTO station(id_station, station_name) VALUES ('55330',"Pyrenees");
INSERT INTO station(id_station, station_name) VALUES ('1742',"Quai de la Gare");
INSERT INTO station(id_station, station_name) VALUES ('1743',"Quai de la Rapée");
INSERT INTO station(id_station, station_name) VALUES ('1744',"Quatre Septembre");
INSERT INTO station(id_station, station_name) VALUES ('1745',"Rambuteau");
INSERT INTO station(id_station, station_name) VALUES ('1659',"Ranelagh");
INSERT INTO station(id_station, station_name) VALUES ('1660',"Raspail");
INSERT INTO station(id_station, station_name) VALUES ('1676',"Réaumur-Sébastopol");
INSERT INTO station(id_station, station_name) VALUES ('1661',"Rennes");
INSERT INTO station(id_station, station_name) VALUES ('1679',"République");
INSERT INTO station(id_station, station_name) VALUES ('1662',"Reuilly-Diderot");
INSERT INTO station(id_station, station_name) VALUES ('1664',"Richard-Lenoir");
INSERT INTO station(id_station, station_name) VALUES ('1665',"Richelieu-Drouot");
INSERT INTO station(id_station, station_name) VALUES ('1666',"Riquet");
INSERT INTO station(id_station, station_name) VALUES ('1667',"Robespierre");
INSERT INTO station(id_station, station_name) VALUES ('1670',"Rome");
INSERT INTO station(id_station, station_name) VALUES ('1672',"Rue de la Pompe (Avenue Georges Mandel)");
INSERT INTO station(id_station, station_name) VALUES ('1673',"Rue des Boulets");
INSERT INTO station(id_station, station_name) VALUES ('1674',"Rue du Bac");
INSERT INTO station(id_station, station_name) VALUES ('1693',"Rue Saint-Maur");
INSERT INTO station(id_station, station_name) VALUES ('1680',"Saint-Ambroise");
INSERT INTO station(id_station, station_name) VALUES ('1681',"Saint-Augustin");
INSERT INTO station(id_station, station_name) VALUES ('22439',"Saint-Denis-Porte de Paris");
INSERT INTO station(id_station, station_name) VALUES ('50399',"Saint-Denis-Universite");
INSERT INTO station(id_station, station_name) VALUES ('1684',"Saint-Fargeau");
INSERT INTO station(id_station, station_name) VALUES ('1685',"Saint-Francois-Xavier");
INSERT INTO station(id_station, station_name) VALUES ('1686',"Saint-Georges");
INSERT INTO station(id_station, station_name) VALUES ('1687',"Saint-Germain des Prés");
INSERT INTO station(id_station, station_name) VALUES ('1688',"Saint-Jacques");
INSERT INTO station(id_station, station_name) VALUES ('1689',"Saint-Lazare");
INSERT INTO station(id_station, station_name) VALUES ('1690',"Saint-Mandé");
INSERT INTO station(id_station, station_name) VALUES ('1691',"Saint-Marcel");
INSERT INTO station(id_station, station_name) VALUES ('1694',"Saint-Michel");
INSERT INTO station(id_station, station_name) VALUES ('1695',"Saint-Paul (Le Marais)");
INSERT INTO station(id_station, station_name) VALUES ('1696',"Saint-Philippe du Roule");
INSERT INTO station(id_station, station_name) VALUES ('1697',"Saint-Placide");
INSERT INTO station(id_station, station_name) VALUES ('1699',"Saint-Sébastien-Froissart");
INSERT INTO station(id_station, station_name) VALUES ('1698',"Saint-Sulpice");
INSERT INTO station(id_station, station_name) VALUES ('1631',"Ségur");
INSERT INTO station(id_station, station_name) VALUES ('1702',"Sentier");
INSERT INTO station(id_station, station_name) VALUES ('1632',"Sèvres-Babylone");
INSERT INTO station(id_station, station_name) VALUES ('1633',"Sèvres-Lecourbe");
INSERT INTO station(id_station, station_name) VALUES ('1621',"Simplon");
INSERT INTO station(id_station, station_name) VALUES ('1622',"Solférino");
INSERT INTO station(id_station, station_name) VALUES ('1627',"Stalingrad");
INSERT INTO station(id_station, station_name) VALUES ('1628',"Strasbourg-Saint-Denis");
INSERT INTO station(id_station, station_name) VALUES ('1630',"Sully-Morland");
INSERT INTO station(id_station, station_name) VALUES ('55329',"Telegraphe");
INSERT INTO station(id_station, station_name) VALUES ('1634',"Temple");
INSERT INTO station(id_station, station_name) VALUES ('1635',"Ternes");
INSERT INTO station(id_station, station_name) VALUES ('1636',"Tolbiac");
INSERT INTO station(id_station, station_name) VALUES ('1638',"Trinité-d'Estienne d'Orves");
INSERT INTO station(id_station, station_name) VALUES ('1639',"Trocadéro");
INSERT INTO station(id_station, station_name) VALUES ('1640',"Tuileries");
INSERT INTO station(id_station, station_name) VALUES ('1643',"Vaneau");
INSERT INTO station(id_station, station_name) VALUES ('1644',"Varenne");
INSERT INTO station(id_station, station_name) VALUES ('1645',"Vaugirard (Adolphe Chérioux)");
INSERT INTO station(id_station, station_name) VALUES ('1646',"Vavin");
INSERT INTO station(id_station, station_name) VALUES ('1648',"Victor Hugo");
INSERT INTO station(id_station, station_name) VALUES ('1650',"Villejuif-Léo Lagrange");
INSERT INTO station(id_station, station_name) VALUES ('1649',"Villejuif-Louis Aragon");
INSERT INTO station(id_station, station_name) VALUES ('1651',"Villejuif-Paul Vaillant Couturier (Hôpital Paul Brousse)");
INSERT INTO station(id_station, station_name) VALUES ('1654',"Villiers");
INSERT INTO station(id_station, station_name) VALUES ('1656',"Volontaires");
INSERT INTO station(id_station, station_name) VALUES ('1657',"Voltaire (Léon Blum)");
INSERT INTO station(id_station, station_name) VALUES ('1658',"Wagram");
INSERT INTO line_station(id_line, id_station) VALUES ('1','1862');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1866');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1632');
INSERT INTO line_station(id_line, id_station) VALUES ('1','2018');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1770');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1908');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1838');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1874');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1911');
INSERT INTO line_station(id_line, id_station) VALUES ('1','2019');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1643');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1942');
INSERT INTO line_station(id_line, id_station) VALUES ('1','54244');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1836');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1994');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1812');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1950');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1717');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1834');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1631');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1837');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1746');
INSERT INTO line_station(id_line, id_station) VALUES ('1','1952');
INSERT INTO line_station(id_line, id_station) VALUES ('2','1679');
INSERT INTO line_station(id_line, id_station) VALUES ('2','55329');
INSERT INTO line_station(id_line, id_station) VALUES ('2','1964');
INSERT INTO line_station(id_line, id_station) VALUES ('2','1855');
INSERT INTO line_station(id_line, id_station) VALUES ('2','1745');
INSERT INTO line_station(id_line, id_station) VALUES ('2','1819');
INSERT INTO line_station(id_line, id_station) VALUES ('2','1792');
INSERT INTO line_station(id_line, id_station) VALUES ('2','1988');
INSERT INTO line_station(id_line, id_station) VALUES ('2','1849');
INSERT INTO line_station(id_line, id_station) VALUES ('2','1736');
INSERT INTO line_station(id_line, id_station) VALUES ('2','55330');
INSERT INTO line_station(id_line, id_station) VALUES ('2','2004');
INSERT INTO line_station(id_line, id_station) VALUES ('2','1864');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1781');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1732');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1661');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1989');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1918');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1689');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1828');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1638');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1632');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1814');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1622');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1734');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1975');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1656');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1767');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1751');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1865');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1831');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1787');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1645');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1674');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1686');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1813');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1879');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1768');
INSERT INTO line_station(id_line, id_station) VALUES ('3','454595');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1889');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1887');
INSERT INTO line_station(id_line, id_station) VALUES ('3','1885');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1731');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1790');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1818');
INSERT INTO line_station(id_line, id_station) VALUES ('4','22439');
INSERT INTO line_station(id_line, id_station) VALUES ('4','228266');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1927');
INSERT INTO line_station(id_line, id_station) VALUES ('4','22443');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1857');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1783');
INSERT INTO line_station(id_line, id_station) VALUES ('4','50622');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1725');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1816');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1844');
INSERT INTO line_station(id_line, id_station) VALUES ('4','22441');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1751');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1949');
INSERT INTO line_station(id_line, id_station) VALUES ('4','50399');
INSERT INTO line_station(id_line, id_station) VALUES ('4','225437');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1968');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1908');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1705');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1851');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1730');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1689');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1644');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1747');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1872');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1685');
INSERT INTO line_station(id_line, id_station) VALUES ('4','22442');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1931');
INSERT INTO line_station(id_line, id_station) VALUES ('4','1804');
INSERT INTO line_station(id_line, id_station) VALUES ('4','225436');
INSERT INTO line_station(id_line, id_station) VALUES ('5','171507');
INSERT INTO line_station(id_line, id_station) VALUES ('5','2005');
INSERT INTO line_station(id_line, id_station) VALUES ('5','51020');
INSERT INTO line_station(id_line, id_station) VALUES ('5','1964');
INSERT INTO line_station(id_line, id_station) VALUES ('5','1689');
INSERT INTO line_station(id_line, id_station) VALUES ('5','1839');
INSERT INTO line_station(id_line, id_station) VALUES ('5','50055');
INSERT INTO line_station(id_line, id_station) VALUES ('5','50047');
INSERT INTO line_station(id_line, id_station) VALUES ('5','1813');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1913');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1986');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1846');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1855');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1774');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1839');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1662');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1953');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1640');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1938');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1709');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1695');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1802');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1850');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1809');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1716');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1758');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1733');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1690');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1949');
INSERT INTO line_station(id_line, id_station) VALUES ('6','2000');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1924');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1962');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1964');
INSERT INTO line_station(id_line, id_station) VALUES ('6','1885');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1741');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1714');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1670');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1749');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1984');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1790');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1861');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1635');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1627');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1999');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1654');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1892');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1758');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1972');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1754');
INSERT INTO line_station(id_line, id_station) VALUES ('7','2004');
INSERT INTO line_station(id_line, id_station) VALUES ('7','2009');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1784');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1787');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1648');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1978');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1868');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1893');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1995');
INSERT INTO line_station(id_line, id_station) VALUES ('7','1953');
INSERT INTO line_station(id_line, id_station) VALUES ('8','1684');
INSERT INTO line_station(id_line, id_station) VALUES ('8','1736');
INSERT INTO line_station(id_line, id_station) VALUES ('8','1929');
INSERT INTO line_station(id_line, id_station) VALUES ('8','1782');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1852');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1988');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1708');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1928');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1779');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1722');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1740');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1744');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1693');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1658');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1826');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1915');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1634');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1807');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1676');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1654');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1689');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1721');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1929');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1982');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1679');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1741');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1771');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1702');
INSERT INTO line_station(id_line, id_station) VALUES ('9','1930');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1676');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1628');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1969');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1726');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1828');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1770');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1694');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1964');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1914');
INSERT INTO line_station(id_line, id_station) VALUES ('10','466736');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1753');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1697');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1660');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1698');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1646');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1720');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1801');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1621');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1999');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1981');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1687');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1841');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1902');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1961');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1751');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1960');
INSERT INTO line_station(id_line, id_station) VALUES ('10','1842');
INSERT INTO line_station(id_line, id_station) VALUES ('11','2011');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1861');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1933');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1664');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1842');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1769');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1853');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1941');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1838');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1728');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1912');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1773');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1841');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1679');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1789');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1627');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1859');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1743');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1691');
INSERT INTO line_station(id_line, id_station) VALUES ('11','1882');
INSERT INTO line_station(id_line, id_station) VALUES ('11','2010');
INSERT INTO line_station(id_line, id_station) VALUES ('11','2000');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1890');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1953');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1751');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1907');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1781');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1910');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1785');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1789');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1660');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1780');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1874');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1906');
INSERT INTO line_station(id_line, id_station) VALUES ('12','2003');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1633');
INSERT INTO line_station(id_line, id_station) VALUES ('12','2005');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1688');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1940');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1758');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1902');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1761');
INSERT INTO line_station(id_line, id_station) VALUES ('12','2007');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1639');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1959');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1901');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1742');
INSERT INTO line_station(id_line, id_station) VALUES ('12','2012');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1867');
INSERT INTO line_station(id_line, id_station) VALUES ('12','1848');
INSERT INTO line_station(id_line, id_station) VALUES ('13','1792');
INSERT INTO line_station(id_line, id_station) VALUES ('13','1861');
INSERT INTO line_station(id_line, id_station) VALUES ('13','1806');
INSERT INTO line_station(id_line, id_station) VALUES ('13','1737');
INSERT INTO line_station(id_line, id_station) VALUES ('13','2016');
INSERT INTO line_station(id_line, id_station) VALUES ('13','2014');
INSERT INTO line_station(id_line, id_station) VALUES ('13','1936');
INSERT INTO line_station(id_line, id_station) VALUES ('13','1900');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1719');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1866');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1815');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1649');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1735');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1636');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1795');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1964');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1957');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1820');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1771');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1711');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1841');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1963');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1869');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1774');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1706');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1793');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1651');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1630');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1718');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1789');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1992');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1650');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1738');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1923');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1786');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1888');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1724');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1666');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1894');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1800');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1627');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1788');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1939');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1944');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1806');
INSERT INTO line_station(id_line, id_station) VALUES ('14','1712');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1899');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1874');
INSERT INTO line_station(id_line, id_station) VALUES ('15','2017');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1665');
INSERT INTO line_station(id_line, id_station) VALUES ('15','2015');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1958');
INSERT INTO line_station(id_line, id_station) VALUES ('15','2000');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1803');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1662');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1925');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1750');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1771');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1699');
INSERT INTO line_station(id_line, id_station) VALUES ('15','397629');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1997');
INSERT INTO line_station(id_line, id_station) VALUES ('15','54166');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1723');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1835');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1628');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1813');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1909');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1919');
INSERT INTO line_station(id_line, id_station) VALUES ('15','21582');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1897');
INSERT INTO line_station(id_line, id_station) VALUES ('15','21583');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1973');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1808');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1857');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1679');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1671');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1901');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1715');
INSERT INTO line_station(id_line, id_station) VALUES ('15','23674');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1885');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1798');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1917');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1951');
INSERT INTO line_station(id_line, id_station) VALUES ('15','1898');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1957');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1876');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1817');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1665');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1896');
INSERT INTO line_station(id_line, id_station) VALUES ('16','2006');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1955');
INSERT INTO line_station(id_line, id_station) VALUES ('16','2015');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1829');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1852');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1836');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1680');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1729');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1681');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1628');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1860');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1657');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1679');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1672');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1727');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1924');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1769');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1858');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1916');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1639');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1837');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1747');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1696');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1659');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1671');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1710');
INSERT INTO line_station(id_line, id_station) VALUES ('16','55372');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1673');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1937');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1980');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1667');
INSERT INTO line_station(id_line, id_station) VALUES ('16','1758');
INSERT INTO line_station(id_line, id_station) VALUES ('17','2022');
INSERT INTO line_station(id_line, id_station) VALUES ('17','2021');
